name: Run Python Script

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  run-script:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Check out the repository code

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # Use Python 3.x

      - name: Run Python script
        run: python script.py  # Run the script
